[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dash2"
version = "0.1.0"
description = "Dashboard application"
requires-python = ">=3.9"
